modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/Spice-of-Life-Onion/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="solonion"
    logoFile="solonion.png"
    version="1.2.9"
    displayName="Spice of Life Onion"
    displayURL="https://modrinth.com/mod/spice-of-life-onion"
    authors="tarinoita, CreativeMD"
    description='''A mod designed to encourage dietary variety by rewarding the player with customizable benefits depending on how diverse their diet is.'''

[[dependencies.solonion]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.solonion]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.solonion]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.12.3,)"

